### ISSUE TITLE
classpath is too long when compile gwt

### ISSUE THREAD

**Issue by bill2004158** [gwt-maven-plugin/gwt-maven-plugin#113] opened 2015-05-15 11:07 UTC
classpath is too long when compile gwt, and that will cause such error:
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
    at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:675)
    at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLineAsCallable(CommandLineUtils.java:134)
    at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:105)
    at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:74)
    at org.codehaus.mojo.gwt.shell.JavaCommand.execute(JavaCommand.java:322)
    ... 24 more
Caused by: java.io.IOException: Cannot run program "C:\Program Files\Java\jdk1.7.0_75\jre\bin\java": CreateProcess error=206, ??????Ȱ)???
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at java.lang.Runtime.exec(Runtime.java:617)
    at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:655)
    ... 28 more
Caused by: java.io.IOException: CreateProcess error=206, ??????Ȱ)???
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
    at java.lang.ProcessImpl.start(ProcessImpl.java:136)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 30 more

so can we impl like this options to avoid such problem?
http://stackoverflow.com/questions/10519558/createprocess-error-206-the-filename-or-extension-is-too-long-when-running-main
http://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows

**Comment by bill2004158** [comment] 2015-05-15 11:12
I saw this comments about this issue
https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/2b60f6306fdce410399dd4c76c07ea91884abb3b/src/main/java/org/codehaus/mojo/gwt/shell/JavaCommand.java#L298

but we can fix that?

**Comment by pwilkin** [comment] 2016-02-01 15:24
Yes, there is even a fork that gets it done by moving the classpath to a temporary external file. 

Please merge it in the main branch, can't compile some projects without it. 

https://github.com/gwt-maven-plugin/gwt-maven-plugin/compare/master...manstis:master

**Comment by pwilkin** [comment] 2016-04-14 12:29
Any updates on this? The pull request has been waiting for 2 months already...

**Comment by pwilkin** [comment] 2016-08-17 16:17
Bump? Not everyone compiles things on *nix systems. The lack of this fix makes it impossible to compile some solutions with long dependency lists (eg. KIE, jBPM) on Windows.

**Comment by ibaca** [comment] 2016-08-17 18:46
Using the same classpath between the client and the server is the main problem, please you really should try to migrate to https://github.com/tbroyer/gwt-maven-plugin, I'll try to help if you have any dificulties, this is a migration guide https://tbroyer.github.io/gwt-maven-plugin/migrating.html and this archetype (https://github.com/tbroyer/gwt-maven-archetypes/tree/master/modular-webapp/src/main/resources/archetype-resources) contains a perfect client/shared/server configuration. Please, this not only should fix your problem, this probably improve your compilation times and your development lifecycle. It's far better that this one, makes no sense trying to fix this plugin, even more because this plugin facilitates (or encourage) bad practices like sharing the client/server classpath. Please, try it out.

**Comment by ibaca** [comment] 2016-08-23 16:10
Hi @pwilkin, did you try the new plugin? so, did you split your project with separate client and server classpaths? This should improve compilations times and your workflow in general, if you are not getting good results please ask any doubt because this configuration should really improve how you develop GWT applications!

**Comment by pwilkin** [comment] 2016-08-26 13:51
The problem is, I need this to build projects that are not created/maintained by me (namely, KIE/jBPM Designer). While I agree with you that the approach of decoupling server-side libraries from client-side libraries is the way to go, I do not see the people who are maintaining the respective projects (and usually building it on Linux) devoting the time to refactoring their entire huge project. I need to make do with what I have, which is a long classpath which I am given.

**Comment by ibaca** [comment] 2016-10-18 19:35
Ups, closed by the commit comment. I have made a small but dangerous change, please @pwilkin test if this actually fix your problem, and doesn't break anything else 😜.

**Comment by ibaca** [comment] 2016-11-20 19:50
This should be fixed... if still fails, comment including a link to the failing project.

**Closed by ibaca** 2016-11-20 19:50 UTC

**Comment by Catscratch** [comment] 2018-09-10 07:34
Hi.

I still got the problem in 2.8.2. What's the state here?

`
[INFO] java.io.IOException: Cannot run program "C:\Program Files\java\openjdk\jre\bin\java": CreateProcess error=206, The filename or extension is too long
[INFO] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[INFO] 	at com.google.gwt.dev.ExternalPermutationWorkerFactory.launchExternalWorker(ExternalPermutationWorkerFactory.java:282)
[INFO] 	at com.google.gwt.dev.ExternalPermutationWorkerFactory.getWorkers(ExternalPermutationWorkerFactory.java:374)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory.createWorkers(PermutationWorkerFactory.java:351)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory.compilePermutations(PermutationWorkerFactory.java:254)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:211)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:219)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.io.IOException: CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang
[INFO] 	at java.lang.ProcessImpl.create(Native Method)
[INFO] 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[INFO] 	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[INFO] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[INFO] 	... 12 more
`

**Comment by eliasbalasis** [comment] 2021-04-22 13:00
I confirm the same issue with GWT 2.8.2 and Windows 10

This is a well known and too old Windows OS limitation, ironically still present after decades of supposed evolution :-)

Loading the classpath from a file would be very much welcome but sadly it seems this hasn't made it yet to the latest GWT Maven Plugin release.
