### ISSUE TITLE
<style> ignored for gwt:test

### ISSUE THREAD

**Issue by cpovirk** [gwt-maven-plugin/gwt-maven-plugin#153] opened 2017-10-26 15:45 UTC
As best I can tell, setting `<style>` or `-Dgwt.style` has no effect on the output in `target/www-test/com.google.common.primitives.testModule.JUnit/*.cache.js`.

I passed `-e -X` to Maven, and I see no sign of a `-style` argument in the GWT `test` goal's "Execute command." However, I do see such an argument when using `compile`, and I'm able to get `DETAILED` output there on request.

This fits with the fact that I see `-style` set [by the `compile` code](https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/2b09afb22ff780964aa45ad56521ef732dee1af1/src/main/java/org/codehaus/mojo/gwt/shell/CompileMojo.java#L451) but [not by the `test` code](https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/2b09afb22ff780964aa45ad56521ef732dee1af1/src/main/java/org/codehaus/mojo/gwt/shell/TestMojo.java). Other options (e.g., `draftCompile`) appear to be passed through fine, as you'd expect from the source code.

(I tried filing this at http://jira.codehaus.org/browse/MGWT, linked from https://gwt-maven-plugin.github.io/gwt-maven-plugin/issue-tracking.html, but I got a DNS error.)

(I understand that there's now the new https://github.com/tbroyer/gwt-maven-plugin, but AFAICT it doesn't support tests yet.)

**Comment by ibaca** [comment] 2017-10-26 16:10
Creating the issue here is fine, PR even better 😉 BUT, as you have noticed, there is a new plugin which hehe nowadays it is not so new, and yep! it supports tests too! it is just better so I strongly encourage to migrate to the new one. In the best case, if the issue is fixed in this plugin probably it doesn't get released until the next GWT release, pretty sad but this a many other bad decision (or just difficult to know at the beginning) was the motivation to create the new one.

**Comment by ibaca** [comment] 2020-05-14 21:17
Closed due to inactivity.

**Closed by ibaca** 2020-05-14 21:17 UTC
